const ASSETS_BASE_URL = process.env.PUBLIC_ASSETS_URL || 'http://localhost:3000/assets'

export const avatarLibrary = [
  { id: 'default', name: 'Default Avatar', url: `${ASSETS_BASE_URL}/avatar.vrm` },
  { id: 'aesthetica', name: 'Aesthetica', url: `${ASSETS_BASE_URL}/Aesthetica_VRM.vrm` },
  { id: 'alwayswatching', name: 'AlwaysWatching', url: `${ASSETS_BASE_URL}/AlwaysWatching_VRM.vrm` },
  { id: 'amazonas', name: 'Amazonas', url: `${ASSETS_BASE_URL}/Amazonas_VRM.vrm` },
  { id: 'anchor', name: 'Anchor', url: `${ASSETS_BASE_URL}/Anchor_VRM.vrm` },
  { id: 'angry', name: 'Angry', url: `${ASSETS_BASE_URL}/Angry_VRM.vrm` },
  { id: 'astrodisco', name: 'Astrodisco', url: `${ASSETS_BASE_URL}/Astrodisco_VRM.vrm` },
  { id: 'astronaut', name: 'Astronaut', url: `${ASSETS_BASE_URL}/Astronaut_VRM.vrm` },
  { id: 'avocado', name: 'Avocado', url: `${ASSETS_BASE_URL}/Avocado_VRM.vrm` },
  { id: 'bacondude', name: 'Bacondude', url: `${ASSETS_BASE_URL}/Bacondude_VRM.vrm` },
  { id: 'baldman', name: 'Baldman', url: `${ASSETS_BASE_URL}/Baldman_VRM.vrm` },
  { id: 'bigbro', name: 'BigBro', url: `${ASSETS_BASE_URL}/BigBro_VRM.vrm` },
  { id: 'bloody', name: 'Bloody', url: `${ASSETS_BASE_URL}/Bloody_VRM.vrm` },
  { id: 'bullidan', name: 'Bullidan', url: `${ASSETS_BASE_URL}/Bullidan_VRM.vrm` },
  { id: 'butter', name: 'Butter', url: `${ASSETS_BASE_URL}/Butter_VRM.vrm` },
  { id: 'cactusboy', name: 'CactusBoy', url: `${ASSETS_BASE_URL}/CactusBoy_VRM.vrm` },
  { id: 'candycane', name: 'CandyCane', url: `${ASSETS_BASE_URL}/CandyCane_VRM.vrm` },
  { id: 'cappy', name: 'Cappy', url: `${ASSETS_BASE_URL}/Cappy_VRM.vrm` },
  { id: 'captainlobster', name: 'CaptainLobster', url: `${ASSETS_BASE_URL}/CaptainLobster_VRM.vrm` },
  { id: 'carrot', name: 'Carrot', url: `${ASSETS_BASE_URL}/Carrot_VRM.vrm` },
  { id: 'chad', name: 'Chad', url: `${ASSETS_BASE_URL}/Chad_VRM.vrm` },
  { id: 'chill', name: 'Chill', url: `${ASSETS_BASE_URL}/Chill_VRM.vrm` },
  { id: 'chilli', name: 'Chilli', url: `${ASSETS_BASE_URL}/Chilli_VRM.vrm` },
  { id: 'clown', name: 'Clown', url: `${ASSETS_BASE_URL}/Clown_VRM.vrm` },
  { id: 'coffee', name: 'Coffee', url: `${ASSETS_BASE_URL}/Coffee_VRM.vrm` },
  { id: 'confirmed', name: 'Confirmed', url: `${ASSETS_BASE_URL}/Confirmed_VRM.vrm` },
  { id: 'cookieman', name: 'Cookieman', url: `${ASSETS_BASE_URL}/Cookieman_VRM.vrm` },
  { id: 'coolalien', name: 'CoolAlien', url: `${ASSETS_BASE_URL}/CoolAlien_VRM.vrm` },
  { id: 'coolbanana', name: 'CoolBanana', url: `${ASSETS_BASE_URL}/CoolBanana_VRM.vrm` },
  { id: 'coolchoco', name: 'CoolChoco', url: `${ASSETS_BASE_URL}/CoolChoco_VRM.vrm` },
  { id: 'crimsom', name: 'Crimsom', url: `${ASSETS_BASE_URL}/Crimsom_VRM.vrm` },
  { id: 'cubiq', name: 'Cubiq', url: `${ASSETS_BASE_URL}/Cubiq_VRM.vrm` },
  { id: 'cucumber', name: 'Cucumber', url: `${ASSETS_BASE_URL}/Cucumber_VRM.vrm` },
  { id: 'david', name: 'David', url: `${ASSETS_BASE_URL}/David_VRM.vrm` },
  { id: 'devil', name: 'Devil', url: `${ASSETS_BASE_URL}/Devil_VRM.vrm` },
  { id: 'dinokid', name: 'DinoKid', url: `${ASSETS_BASE_URL}/DinoKid_VRM.vrm` },
  { id: 'disturbingeyes', name: 'DisturbingEyes', url: `${ASSETS_BASE_URL}/DisturbingEyes_VRM.vrm` },
  { id: 'dracula', name: 'Dracula', url: `${ASSETS_BASE_URL}/Dracula_VRM.vrm` },
  { id: 'eggplant', name: 'Eggplant', url: `${ASSETS_BASE_URL}/Eggplant_VRM.vrm` },
  { id: 'erika', name: 'Erika', url: `${ASSETS_BASE_URL}/Erika_VRM.vrm` },
  { id: 'expol', name: 'Expol', url: `${ASSETS_BASE_URL}/Expol_VRM.vrm` },
  { id: 'eyelids', name: 'Eyelids', url: `${ASSETS_BASE_URL}/Eyelids_VRM.vrm` },
  { id: 'ferk', name: 'Ferk', url: `${ASSETS_BASE_URL}/Ferk_VRM.vrm` },
  { id: 'franky', name: 'Franky', url: `${ASSETS_BASE_URL}/Franky_VRM.vrm` },
  { id: 'froggy', name: 'Froggy', url: `${ASSETS_BASE_URL}/Froggy_VRM.vrm` },
  { id: 'fungus', name: 'Fungus', url: `${ASSETS_BASE_URL}/Fungus_VRM.vrm` },
  { id: 'ghost', name: 'Ghost', url: `${ASSETS_BASE_URL}/Ghost_VRM.vrm` },
  { id: 'goodtomato', name: 'GoodTomato', url: `${ASSETS_BASE_URL}/GoodTomato_VRM.vrm` },
  { id: 'horrornurse', name: 'HorrorNurse', url: `${ASSETS_BASE_URL}/HorrorNurse_VRM.vrm` },
  { id: 'hotdog', name: 'Hotdog', url: `${ASSETS_BASE_URL}/Hotdog_VRM.vrm` },
  { id: 'hugo', name: 'Hugo', url: `${ASSETS_BASE_URL}/Hugo_VRM.vrm` },
  { id: 'icecream', name: 'IceCream', url: `${ASSETS_BASE_URL}/IceCream_VRM.vrm` },
  { id: 'jennifer', name: 'Jennifer', url: `${ASSETS_BASE_URL}/Jennifer_VRM.vrm` },
  { id: 'jimmy', name: 'Jimmy', url: `${ASSETS_BASE_URL}/Jimmy_VRM.vrm` },
  { id: 'kate', name: 'Kate', url: `${ASSETS_BASE_URL}/Kate_VRM.vrm` },
  { id: 'kyle', name: 'Kyle', url: `${ASSETS_BASE_URL}/Kyle_VRM.vrm` },
  { id: 'lilbro', name: 'LilBro', url: `${ASSETS_BASE_URL}/LilBro_VRM.vrm` },
  { id: 'lydia', name: 'Lydia', url: `${ASSETS_BASE_URL}/Lydia_VRM.vrm` },
  { id: 'mafiossini', name: 'Mafiossini', url: `${ASSETS_BASE_URL}/Mafiossini_VRM.vrm` },
  { id: 'mikel', name: 'Mikel', url: `${ASSETS_BASE_URL}/Mikel_VRM.vrm` },
  { id: 'milk', name: 'Milk', url: `${ASSETS_BASE_URL}/Milk_VRM.vrm` },
  { id: 'mint', name: 'Mint', url: `${ASSETS_BASE_URL}/Mint_VRM.vrm` },
  { id: 'mummy', name: 'Mummy', url: `${ASSETS_BASE_URL}/Mummy_VRM.vrm` },
  { id: 'muscary', name: 'Muscary', url: `${ASSETS_BASE_URL}/Muscary_VRM.vrm` },
  { id: 'mushy', name: 'Mushy', url: `${ASSETS_BASE_URL}/Mushy_VRM.vrm` },
  { id: 'nightmare', name: 'Nightmare', url: `${ASSETS_BASE_URL}/Nightmare_VRM.vrm` },
  { id: 'observer', name: 'Observer', url: `${ASSETS_BASE_URL}/Observer_VRM.vrm` },
  { id: 'oldmoustache', name: 'OldMoustache', url: `${ASSETS_BASE_URL}/OldMoustache_VRM.vrm` },
  { id: 'olivia', name: 'Olivia', url: `${ASSETS_BASE_URL}/Olivia_VRM.vrm` },
  { id: 'pepo', name: 'Pepo', url: `${ASSETS_BASE_URL}/Pepo_VRM.vrm` },
  { id: 'pipe', name: 'Pipe', url: `${ASSETS_BASE_URL}/Pipe_VRM.vrm` },
  { id: 'polybot', name: 'Polybot', url: `${ASSETS_BASE_URL}/Polybot_VRM.vrm` },
  { id: 'polydancer', name: 'Polydancer', url: `${ASSETS_BASE_URL}/Polydancer_VRM.vrm` },
  { id: 'present', name: 'Present', url: `${ASSETS_BASE_URL}/Present_VRM.vrm` },
  { id: 'pumpkin', name: 'Pumpkin', url: `${ASSETS_BASE_URL}/Pumpkin_VRM.vrm` },
  { id: 'rabbit', name: 'Rabbit', url: `${ASSETS_BASE_URL}/Rabbit_VRM.vrm` },
  { id: 'retroman', name: 'Retroman', url: `${ASSETS_BASE_URL}/Retroman_VRM.vrm` },
  { id: 'ro', name: 'Ro', url: `${ASSETS_BASE_URL}/Ro_VRM.vrm` },
  { id: 'robert', name: 'Robert', url: `${ASSETS_BASE_URL}/Robert_VRM.vrm` },
  { id: 'rose', name: 'Rose', url: `${ASSETS_BASE_URL}/Rose_VRM.vrm` },
  { id: 'saintclaus', name: 'SaintClaus', url: `${ASSETS_BASE_URL}/SaintClaus_VRM.vrm` },
  { id: 'samuela', name: 'Samuela', url: `${ASSETS_BASE_URL}/Samuela_VRM.vrm` },
  { id: 'scarecrow', name: 'Scarecrow', url: `${ASSETS_BASE_URL}/Scarecrow_VRM.vrm` },
  { id: 'shiro', name: 'Shiro', url: `${ASSETS_BASE_URL}/Shiro_VRM.vrm` },
  { id: 'skelly', name: 'Skelly', url: `${ASSETS_BASE_URL}/Skelly_VRM.vrm` },
  { id: 'skull', name: 'Skull', url: `${ASSETS_BASE_URL}/Skull_VRM.vrm` },
  { id: 'snowy', name: 'Snowy', url: `${ASSETS_BASE_URL}/Snowy_VRM.vrm` },
  { id: 'sticker', name: 'Sticker', url: `${ASSETS_BASE_URL}/Sticker_VRM.vrm` },
  { id: 'teddy', name: 'Teddy', url: `${ASSETS_BASE_URL}/Teddy_VRM.vrm` },
  { id: 'toiletpaper', name: 'ToiletPaper', url: `${ASSETS_BASE_URL}/ToiletPaper_VRM.vrm` },
  { id: 'toothpaste', name: 'Toothpaste', url: `${ASSETS_BASE_URL}/Toothpaste_VRM.vrm` },
  { id: 'udom', name: 'Udom', url: `${ASSETS_BASE_URL}/Udom_VRM.vrm` },
  { id: 'wambo', name: 'Wambo', url: `${ASSETS_BASE_URL}/Wambo_VRM.vrm` },
  { id: 'watermelon', name: 'Watermelon', url: `${ASSETS_BASE_URL}/Watermelon_VRM.vrm` },
  { id: 'weirdflexbutok', name: 'WeirdFlexButOk', url: `${ASSETS_BASE_URL}/WeirdFlexButOk_VRM.vrm` },
  { id: 'wirefriend', name: 'WireFriend', url: `${ASSETS_BASE_URL}/WireFriend_VRM.vrm` },
  { id: 'witch', name: 'Witch', url: `${ASSETS_BASE_URL}/Witch_VRM.vrm` },
  { id: 'wizzir', name: 'Wizzir', url: `${ASSETS_BASE_URL}/Wizzir_VRM.vrm` },
  { id: 'wolfman', name: 'Wolfman', url: `${ASSETS_BASE_URL}/Wolfman_VRM.vrm` },
  { id: 'xmastree', name: 'XmasTree', url: `${ASSETS_BASE_URL}/XmasTree_VRM.vrm` },
  { id: 'zombie', name: 'Zombie', url: `${ASSETS_BASE_URL}/Zombie_VRM.vrm` },
]

/**
 * Resolve an avatar reference to a full URL.
 *
 * Supported formats:
 *   - Full URL: "https://..." or "http://..." — pass through
 *   - Asset protocol: "asset://..." — pass through (Hyperfy resolves internally)
 *   - Library ref: "library:<id>" or just "<id>" — resolve from avatarLibrary
 *
 * Returns null for unknown references.
 */
export function resolveAvatarRef(ref) {
  if (!ref || typeof ref !== 'string') return null
  if (ref.startsWith('http://') || ref.startsWith('https://')) return ref
  if (ref.startsWith('asset://')) return ref
  const id = ref.startsWith('library:') ? ref.slice('library:'.length) : ref
  const entry = avatarLibrary.find(a => a.id === id)
  return entry ? entry.url : null
}
